use_frameworks!

platform :ios, '12.4'

target 'Apple-Cocoapod-KochavaCore_Example' do
  pod 'Apple-Cocoapod-KochavaCore', :path => '../'

  target 'Apple-Cocoapod-KochavaCore_Tests' do
    inherit! :search_paths

    
  end
end
